name = "ocr-api-bh-assurance"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "6435a77d3ce17b7de468c6618e7b2b14"

# ============ DEV ============
[env.dev]
name = "ocr-api-bh-assurance-dev"

# ============ STAGING ============
[env.staging]
name = "ocr-api-bh-assurance-staging"

# ============ PROD ============
[env.prod]
name = "ocr-api-bh-assurance"
